In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = 'test.txt'

In [44]:
df = pd.read_table(file_path, delimiter='  ')
df
print(df.loc[df['id'] == 24, 'id'])

22    24
Name: id, dtype: int64


/tmp/ipykernel_1491081/1775306632.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_table(file_path, delimiter='  ')


In [31]:

df.loc[df['id'] == 24, 'id'] = 99
df

id    x1   y1   w   h  frame      conf  cls  x_anchor  y_anchor
0    1  2132  490  36  71    290  0.929146    1      2167       526
1    2  2296  368  22  50    290  0.924701    1      2321       390
2    3  2043  326  19  42    290  0.886539    1      2064       345
3    4  2072  355  17  53    290  0.900021    1      2098       372
4    5  1907  257  17  33    290  0.783417    1      1923       274
5    6  1692  224  13  38    290  0.894947    1      1711       237
6    7  2401  320  17  51    290  0.904776    1      2426       337
7    8  1716  148  13  29    290  0.868722    1      1730       161
8    9  2376  368  22  53    290  0.898749    1      2402       390
9   10  2021  155  11  30    290  0.854649    2      2036       166
10  11  1943  207  13  33    290  0.885604    1      1959       220
11  12  2270  201  17  41    290  0.862534    1      2290       218
12  13  2163  149  12  27    290  0.877829    1      2176       161
13  14  1902  279  16  49    290  0.878666    1      1926       295
14  15  2024  136  14  27    290  0.821368    1      2037       150
15  16  2078  183  11  31    290  0.850877    1      2093       194
16  19  2031  299  16  38    290  0.897703    1      2050       315
17  20  2052  169  14  30    290  0.872374    1      2067       183
18  21  2001  224  13  33    290  0.890934    1      2017       237
19  23  2608  189  17  31    290  0.865630    1      2623       206
20  18  1403  192  13  33    290  0.841796    1      1419       205
21  22  1989   97   8  20    290  0.811561    1      1999       105
22  99  2013  628  30  33    290  0.289918    1      2029       658

In [55]:
import numpy as np
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment

# Пример данных: два списка координат
coords1 = np.array([[1, 2], [5, 6], [3, 4]])
coords2 = np.array([[5, 6], [7, 8]])
coords1 = coords1[coords1[:, 0].argsort()]
coords2 = coords2[coords2[:, 0].argsort()]
print(coords1)
print(coords2)

# Вычисление матрицы евклидовых расстояний
distance_matrix = cdist(coords1, coords2, metric='euclidean')

# Решение задачи сопоставления с минимальной стоимостью (расстоянием)
row_ind, col_ind = linear_sum_assignment(distance_matrix)

# Печать результатов сопоставления
for i, j in zip(row_ind, col_ind):
    print(f"coords1[{i}] -> coords2[{j}], расстояние: {distance_matrix[i, j]}")

print("Матрица расстояний:")
print(distance_matrix)


[[1 2]
 [3 4]
 [5 6]]
[[5 6]
 [7 8]]
coords1[1] -> coords2[1], расстояние: 5.656854249492381
coords1[2] -> coords2[0], расстояние: 0.0
Матрица расстояний:
[[5.65685425 8.48528137]
 [2.82842712 5.65685425]
 [0.         2.82842712]]


In [56]:
d = {1:11, 2:22, 3:33}
if 2 in d.keys():
    print(d[2])
            

22
