In [11]:
import pandas as pd
import numpy as np

In [21]:
file_path = 'test.txt'

In [22]:
df = pd.read_table(file_path, delimiter='  ')
#print(df)
df[['id']] = df.loc[df['id'].isin([24, 2]),  'id'] = [33,44]
print(df)

/tmp/ipykernel_27504/2465166153.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_table(file_path, delimiter='  ')


ValueError: Columns must be same length as key

In [71]:
df.loc[df['id'] == 24, 'id'] = 99
df = df.sort_values(['x1', 'y1'], ascending=[True, True]).reset_index(drop=True)
for _, d in df.iterrows():
    x = d[['x_anchor', 'y_anchor']].values
    print(x.shape)
    break

(2,)


In [62]:
df.loc[1,'id']

6

In [55]:
import numpy as np
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment

# Пример данных: два списка координат
coords1 = np.array([[1, 2], [5, 6], [3, 4]])
coords2 = np.array([[5, 6], [7, 8]])
coords1 = coords1[coords1[:, 0].argsort()]
coords2 = coords2[coords2[:, 0].argsort()]
print(coords1)
print(coords2)

# Вычисление матрицы евклидовых расстояний
distance_matrix = cdist(coords1, coords2, metric='euclidean')

# Решение задачи сопоставления с минимальной стоимостью (расстоянием)
row_ind, col_ind = linear_sum_assignment(distance_matrix)

# Печать результатов сопоставления
for i, j in zip(row_ind, col_ind):
    print(f"coords1[{i}] -> coords2[{j}], расстояние: {distance_matrix[i, j]}")

print("Матрица расстояний:")
print(distance_matrix)


[[1 2]
 [3 4]
 [5 6]]
[[5 6]
 [7 8]]
coords1[1] -> coords2[1], расстояние: 5.656854249492381
coords1[2] -> coords2[0], расстояние: 0.0
Матрица расстояний:
[[5.65685425 8.48528137]
 [2.82842712 5.65685425]
 [0.         2.82842712]]


In [74]:
import json
from ultralytics import YOLO

with open('/home/skorp321/Projects/panorama/data/soccer_field_anno/annotations/person_keypoints_default.json', 'r') as file:            
    data = file.read()

# Преобразование строки в словарь с помощью метода loads
data_dict = json.loads(data)

categoris = data_dict['categories'][0]['keypoints']
df = data_dict['annotations'][0]['keypoints']

res = {}
for i, data in enumerate(categoris):
    res[data] = df[(i*3):((i+1)*3)-1]
    
sorted_list = sorted(res.items(), key=lambda x: x[0])

# Преобразуем список обратно в словарь
sorted_dict = {k: v for k, v in sorted_list}
print(sorted_dict)

with open('/home/skorp321/Projects/panorama/data/Swiss_vs_Slovakia-panoramic_video_anno/annotations/person_keypoints_default.json', 'r') as file:            
    data = file.read()

# Преобразование строки в словарь с помощью метода loads
data_dict = json.loads(data)

categoris = data_dict['categories'][0]['keypoints']
df = data_dict['annotations'][0]['keypoints']

res = {}
for i, data in enumerate(categoris):
    res[data] = df[(i*3):((i+1)*3)-1]
    
sorted_list = sorted(res.items(), key=lambda x: x[0])

# Преобразуем список обратно в словарь
sorted_dict = {k: v for k, v in sorted_list}
print(sorted_dict)

model_keypoint = YOLO('/home/skorp321/Projects/panorama/models/yolov8m_keypoints.pt')
print(model_keypoint.names)
            

{'cb': [413.07, 507.07], 'cp': [412.54, 259.73], 'ct': [413.18, 13.8], 'lcb': [34.04, 505.4], 'lct': [33.83, 13.55], 'lpb': [151.91, 403.07], 'lpt': [152.23, 114.22], 'rcb': [792.31, 507.19], 'rct': [792.31, 12.39], 'rpb': [674.23, 407.29], 'rpt': [672.84, 113.57]}
{'cb': [1921.36, 595.31], 'cp': [1941.96, 212.3], 'ct': [1948.33, 108.58], 'lcb': [33.23, 598.67], 'lct': [1420.99, 107.97], 'lpb': [1085.1, 364.47], 'lpt': [1522.63, 140.11], 'rcb': [3823.49, 602.24], 'rct': [2474.79, 107.04], 'rpb': [2780.99, 363.28], 'rpt': [2368.52, 140.16]}
{0: 'TLC', 1: 'TRC', 2: 'TR6MC', 3: 'TL6MC', 4: 'TR6ML', 5: 'TL6ML', 6: 'TR18MC', 7: 'TL18MC', 8: 'TR18ML', 9: 'TL18ML', 10: 'TRArc', 11: 'TLArc', 12: 'RML', 13: 'RMC', 14: 'LMC', 15: 'LML', 16: 'BLC', 17: 'BRC', 18: 'BR6MC', 19: 'BL6MC', 20: 'BR6ML', 21: 'BL6ML', 22: 'BR18MC', 23: 'BL18MC', 24: 'BR18ML', 25: 'BL18ML', 26: 'BRArc', 27: 'BLArc'}


In [6]:
import numpy as np

def iou(box1, box2):
    """
    Compute the Intersection Over Union (IoU) of two bounding boxes.

    Parameters
    ----------
    box1 : ndarray
        (x1, y1, x2, y2) of the first box.
    box2 : ndarray
        (x1, y1, x2, y2) of the second box.

    Returns
    -------
    float
        in [0, 1]
    """
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    inter_area = max(0, x2 - x1) * max(0, y2 - y1)

    box1_area = (box1[2] - box1[0]) * (box1[3] - box1[1])
    box2_area = (box2[2] - box2[0]) * (box2[3] - box2[1])

    union_area = box1_area + box2_area - inter_area

    return inter_area / union_area if union_area != 0 else 0

def non_max_suppression(boxes, iou_threshold):
    """
    Perform non-maximum suppression, given a list of boxes with their
    corresponding scores and class labels.

    Parameters
    ----------
    boxes : list of lists or 2D ndarray
        List with elements [x1, y1, x2, y2, score, class_label].
    iou_threshold : float
        Threshold for IoU to determine whether boxes overlap too much.

    Returns
    -------
    list of lists
        Filtered boxes after NMS.
    """
    if len(boxes) == 0:
        return []

    # Sort the boxes by score in descending order
    boxes = sorted(boxes, key=lambda x: x[4], reverse=True)
    picked_boxes = []

    while boxes:
        # Pick the box with the highest score
        current_box = boxes.pop(0)
        picked_boxes.append(current_box)

        # Compare the picked box with the rest of the boxes
        boxes = [box for box in boxes if box[5] != current_box[5] or iou(current_box, box) <= iou_threshold]

    return picked_boxes

# Example usage:
boxes = [
    [100, 100, 210, 210, 0.72, 0],  # x1, y1, x2, y2, score, class_label
    [250, 250, 420, 420, 0.8, 0],
    [220, 220, 320, 320, 0.92, 0],
    [100, 100, 210, 210, 0.72, 1],
    [230, 240, 325, 330, 0.81, 1],
    [220, 230, 315, 340, 0.9, 1]
]

filtered_boxes = non_max_suppression(boxes, iou_threshold=0.1)
print("Filtered boxes after NMS:")
for box in filtered_boxes:
    print(box)

Filtered boxes after NMS:
[220, 220, 320, 320, 0.92, 0]
[220, 230, 315, 340, 0.9, 1]
[100, 100, 210, 210, 0.72, 0]
[100, 100, 210, 210, 0.72, 1]
